// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: character.capnp

#include "character.capnp.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<34> b_9596428744da6ad3 = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
    211, 106, 218,  68, 135,  66, 150, 149,
     23,   0,   0,   0,   1,   0,   0,   0,
    163, 124, 143, 243, 206,  51, 181, 180,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  10,   1,   0,   0,
     37,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     33,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    115, 111, 117, 114,  99, 101,  47,  99,
    104,  97, 114,  97,  99, 116, 101, 114,
     46,  99,  97, 112, 110, 112,  58,  67,
    104,  97, 114,  97,  99, 116, 101, 114,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,   3,   0,   1,   0,
     20,   0,   0,   0,   2,   0,   1,   0,
    110,  97, 109, 101,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_9596428744da6ad3 = b_9596428744da6ad3.words;
#if !CAPNP_LITE
static const uint16_t m_9596428744da6ad3[] = {0};
static const uint16_t i_9596428744da6ad3[] = {0};
const ::capnp::_::RawSchema s_9596428744da6ad3 = {
  0x9596428744da6ad3, b_9596428744da6ad3.words, 34, nullptr, m_9596428744da6ad3,
  0, 1, i_9596428744da6ad3, nullptr, nullptr, { &s_9596428744da6ad3, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
}  // namespace schemas
}  // namespace capnp

// =======================================================================================


// Character
#ifndef _MSC_VER
constexpr uint16_t Character::_capnpPrivate::dataWordSize;
constexpr uint16_t Character::_capnpPrivate::pointerCount;
#endif
#if !CAPNP_LITE
constexpr ::capnp::Kind Character::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Character::_capnpPrivate::schema;
constexpr ::capnp::_::RawBrandedSchema const* Character::_capnpPrivate::brand;
#endif  // !CAPNP_LITE



